input:
  complex_path: ../protein_input/GPCR_DRD2/gpcr_drd2_6lqu_complex_autoprepared.pdb
  pdb_path: ../protein_input/GPCR_DRD2/gpcr_drd2_6lqu_protein_autoprepared.pdb
  sdf_path: ../protein_input/GPCR_DRD2/gpcr_drd2_6lqu_ligand.sdf

parameter:
  box_size: 16
  num_sample: 100, 200, 500
  name: drd2_prepared_0
  protein_title: GPCR_DRD2
  
output:
  output_dir: ../output_test_multiple_numsample/GPCR_DRD2_14nov

models_dir:
  pmdm: /opt/veincent/GenAI_manuscript/models/PMDM
  diffsbdd: /opt/veincent/GenAI_manuscript/models/DiffSBDD
  pocket2mol: /opt/veincent/GenAI_manuscript/models/Pocket2Mol
  pocketflow: /opt/veincent/GenAI_manuscript/models/PocketFlow
  lingo3dmol: /opt/veincent/GenAI_manuscript/models/Lingo3DMol

conda_env:
  pmdm: benchmark_pmdm
  diffsbdd: benchmark_diffsbdd
  pocket2mol: benchmark_pocket2mol
  pocketflow: benchmark_pocketflow
  lingo3dmol: benchmark_lingo3dmol

